### ISSUE TITLE
Bot not generating PR for v0.4.1

### ISSUE THREAD

**Issue by janniklasrose** [conda-forge/chebfun-feedstock#5]
Timeline of events:

1. upstream repo [chebpy/chebpy](https://github.com/chebpy/chebpy) was updated to v0.4.0
2. PR #4 was auto-generated
3. Checks in that PR failed, so PR was **closed** to skip v0.4.0
4. upstream repo [chebpy/chebpy](https://github.com/chebpy/chebpy) was updated to v0.4.1
5. No PR was generated, despite assigning the `bot-rerun` label, re-opening PR, calling `@conda-forge-admin, please rerun bot`
6. Merged PR #4
7. Still no new PR for v0.4.1

**Comment by janniklasrose** [comment]
Would be great if you could have a look at this, @conda-forge/bot !

**Comment by beckermr** [comment]
Hi! Thanks for bumping us. Please check the upstream tags as there appears to be an error: https://github.com/chebpy/chebpy/tags

**Comment by janniklasrose** [comment]
Thank you for the quick response! And for spotting the silly mistake on our end...

**Comment by janniklasrose** [comment]
@beckermr where should I open an issue with a feature request to have the bot reply to the PR if any of the mechanisms (@'ing the bot, adding a label) fail like they did in this case? Unless that already exists or you don't think it's useful.

**Comment by beckermr** [comment]
The bot has no way to know if adding a rerun label has failed in the sense you are saying. Those labels simply have the bot retry making a given PR. When it goes to retry, it may decide that no new PR is needed (e.g., if the PR is a version bump and the repo has had its versioned bumped manually).

**Comment by markrichardson** [comment]
thanks for spotting. my mistake - apologies.

I have re-tagged to v0.4.1, see https://github.com/chebpy/chebpy/releases/tag/v0.4.1
