### ISSUE TITLE
Bot not generating PR for v0.4.3

### ISSUE THREAD

**Issue by janniklasrose** [conda-forge/chebfun-feedstock#7]
Similar to #5 (v0.4.1), but this time it seems the [tags in the upstream repo](https://github.com/chebpy/chebpy/tags) are correct: https://github.com/conda-forge/chebfun-feedstock/issues/5#issuecomment-913831241

**Comment by janniklasrose** [comment]
@beckermr are we missing something obvious here? I didn't expect the bot to generate `V0.4.2` due to the capital v but for `v0.4.3` everything looks correct.

**Comment by beckermr** [comment]
It looks like there was an internal error: https://github.com/regro/cf-graph-countyfair/blob/master/versions/chebfun.json

Might be related to the `v` only tag?

**Comment by janniklasrose** [comment]
Possible, but the `v0.4.1` tag came after `v`. Looks like the error happened 7 days ago with [this commit](https://github.com/regro/cf-graph-countyfair/commit/f15e379f49632c37e429103af76cd788b1957dfb#diff-61f63a3f72cc7cbad06c37b7f56d892a256ea31997df7f5ac31211cd2d7fe621)

@markrichardson Could you delete the `v`-only release on GitHub?

**Comment by markrichardson** [comment]
Deleted v only tag
